In [1]:
import numpy as np
import pandas as pd

In [2]:
def f_function(number):
    result = number ** 2 + 1
    return result

factorial_np = np.vectorize(f_function)
numbers = [1, 2, 3, 4]
numbers_array = np.array(numbers)
print(factorial_np(numbers_array))

[ 2  5 10 17]


In [3]:
# zeros function()
arr = np.zeros((2,3))
arr, arr.shape

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 (2, 3))

In [4]:
# ones function()
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# full() function
arr = np.full((2, 3), 9)
print(arr)

[[9 9 9]
 [9 9 9]]


In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.random.random((2,3))

array([[0.85456984, 0.80935842, 0.14528484],
       [0.64030408, 0.97622323, 0.89826686]])

In [8]:
# arange()
arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(0, 5, 2)
print(arr2)

[0 1 2 3 4]
[0 2 4]


Part One

In [9]:
arr = np.ones((3, 3)) > 0
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [10]:
import numpy as np
arr1 = np . arange (10) . reshape (2 , -1)
arr2 = np . repeat (1 ,10) . reshape (2 , -1)
c = np . concatenate ([ arr1 , arr2 ] , axis =1)
print (" Result : \n", c )

 Result : 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [11]:
import numpy as np
arr = np . array ([1 ,2 ,3])
print ( np . repeat ( arr ,3) )
print ( np . tile ( arr ,3) )

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [12]:
import numpy as np

a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])
print (" Result ", np . where (a <b , b , a ) )

 Result  [6 7 9 8 9 7 5]


Part Two

In [14]:
%gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

UsageError: Line magic function `%gdown` not found.


In [13]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
img = mpimg.imread("./dog.jpeg")
img.shape

FileNotFoundError: [Errno 2] No such file or directory: '/Users/haodo/Documents/AIO/AIO2024_exercises/Module_2/Week_1/dog.jpeg'